name: CI

on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:

  test:
    name: "Tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive
          fetch-depth: 0 # needed for versioning
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 25
          cache: 'gradle'
      - name: Tests
        run: ./gradlew test --stacktrace

  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive
          fetch-depth: 0 # needed for versioning
      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 25
          cache: 'gradle'
      - name: Build with Gradle
        run: ./gradlew :common:buildWebapp :paper:shadowJar --stacktrace
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bluemap-paper-plugin
          path: implementations/paper/build/libs/*-shadow.jar


